### ISSUE TITLE
Move "Solution" between "What is Slicer" and "Features"

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#44]
@rkikinis

Order of solutions:
* SlicerIGT
* Chest Imaging Platform
* SlicerDMRI
* SlicerRT
* SlicerSALT
* SlicerAstro
* SlicerCMF

Ask for one "fancy" image with a description + add this to the image carousel

**Comment by lassoan** [comment]
I'm still not sure what a solution is. A known application area of Slicer, a subcommunity, an extension, a custom application...?

I feel that it is mostly an application area, which could be represented in the website by a page for each. They could loosely follow the same template with sections like this:
- overview, scope, features
- application examples
- tutorials 
- contact information, discourse subcommunity
- relevant extensions

We should consider adding SlicerMorph and SlicerHeart.

Instead of (maybe in addition to) extension names, we should use more meaningful words:
SlicerRT->Radiation therapy, SlicerSALT->Shape analysis, etc.

**Comment by pieper** [comment]
Yes, I agree with @lassoan 's suggestions.  I already contacted Murat and he wants to add SlicerMorph.  Adding SlicerHeart too is a great idea.

We came up with the Solutions name after some discussion so I'd vote to keep it, but adding a definition would definitely help.  

How about: "Slicer Solutions provide custom modules to support distinct fields of work"

**Comment by lassoan** [comment]
I like the "solution" word we just need to agree in what we mean by it.

Software ("custom modules") is an important part, but specialized workflows, tutorials, subcommunity, etc. should be also mentioned.

**Comment by jcfr** [comment]
> which could be represented in the website by a page for each

Agreed. That is great idea.

Was also thinking to have a dedicated page for each "feature" (#19)

**Comment by fedorov** [comment]
> I like the "solution" word we just need to agree in what we mean by it.

👍

**Comment by jcfr** [comment]
> what we mean by it.

I like the "Application area" terminology

What about the following change:

```diff
- Slicer solutions are either collections of extensions or special distributions of Slicer that provide customized package and complete processing pipeline from beginning to end, addressing specific research problems.
+ Slicer solutions are either tutorials, sub-communities, collections of extensions or special distributions of Slicer that provide customized package and complete processing pipeline from beginning to end, addressing specific research problems.
```

**Comment by pieper** [comment]
How about simplifying:

Slicer solutions are customizations for specific use cases and user groups.

**Comment by fedorov** [comment]
> Slicer solutions are customizations for specific use cases and user groups.

What is the difference between a solution and an extension?

**Comment by fedorov** [comment]
I know no one will like this - but maybe instead of "solutions", which I think are not well-defined, we should highlight Slicer communities.

Slicer Communities could be defined as groups of users and developers that are building collections of tools based on Slicer, have demonstrated adoption in the broader community, established documentation/datasets/supporting materials, user support forum, and resources to maintain the momentum.

**Comment by jcfr** [comment]
> What is the difference between a solution and an extension?

See https://discourse.slicer.org/t/its-all-about-transitions-lets-talk-about-slicers-landing-page/113/35?u=jcfr

**Comment by fedorov** [comment]
@jcfr yes, I do remember that discussion. It didn't clear the topic for me.

In addition to the issue with the definition of what "Solution" is, my concern is that the implication of "defined" solutions is that everything else is not a solution. I think for the most part, most extensions aspire to be a "solution" to a specific problem, and provide a "complete processing pipeline from beginning to end". It's just often not easy to define universal "beginning" and "end", especially in research. There is always room for pushing the boundaries. What is "science" for one may be a "tool" or "application" for another one.

Anyway - I am afraid I never "got" the point of Solutions, unfortunately. Sorry for the distraction.

**Comment by jcfr** [comment]
What about simply changing "Solutions" to "Application Areas" ? 

with text like:

```
Each area addresses a specific research problem and my include tutorials, sub-communities, collections of extensions or special distributions of Slicer that provide customized package and complete processing pipeline from beginning to end.
```

**Comment by lassoan** [comment]
Use cases, applications, application areas, solutions, etc. are all kinds of synonyms. Since "solutions" is short and simple, we could use it as a headline, and then use the other terms in its description:

"Each solution represents an application area of 3D Slicer, which may include collection of extensions, tutorials, forum sub-communities, and even custom software distributions tailored to the needs of a specific community. Custom distributions can provide self-contained, end-to-end implementation of specific workflows with simplified user interface."

**Comment by jcfr** [comment]
Closing. Now that "Extensions" section has been folded into the "Features" one, the "Solutions" are displayed just under it.

![image](https://user-images.githubusercontent.com/219043/111672552-746af700-87f0-11eb-8822-9441f0a01bea.png)
