### ISSUE TITLE
Remove example of post, remove feed plugin

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#50]
https://github.com/Slicer/slicer.org/tree/landing-page-redesign/_posts

https://github.com/Slicer/slicer.org/blob/1627a2c62c66531cff1ba98047b2a3099a656c96/Gemfile#L19

https://github.com/Slicer/slicer.org/blob/1627a2c62c66531cff1ba98047b2a3099a656c96/_config.yml#L31

**Comment by jcfr** [comment]
@faiza-a Any objection is we remove these ?

**Comment by faiza-a** [comment]
@jcfr 
no objection. you can remove these feed.
Regarding post: I left one example post in the _post folder, for the side bar example. if we want to have a sidebar on any of our internal pages.
To check that, In commercial-use.md if you change show_sidebar: true. this loads the example post content in the sidebar of page. 
<img width="370" alt="Screen Shot 2020-08-06 at 10 46 20 AM" src="https://user-images.githubusercontent.com/61198087/89546109-33c6ec00-d7d2-11ea-93e8-5dfaba762103.png">
<img width="1471" alt="Screen Shot 2020-08-06 at 10 54 21 AM" src="https://user-images.githubusercontent.com/61198087/89547022-3e35b580-d7d3-11ea-8575-c60adee4501e.png">

We can change it to load some other file on sidebar instead of that example post.
