### ISSUE TITLE
gallery: hard to discover right/left arrow

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#59]
Is there an option for autoscroll ? If not, having bigger arrow would be nice.

From @lassoan

**Comment by faiza-a** [comment]
Fixed in 071e9ef

Changed arrow colors to make more visible

<img width="1792" alt="Screen Shot 2020-08-17 at 6 17 41 PM" src="https://user-images.githubusercontent.com/61198087/90449715-fd347f80-e0b5-11ea-9a22-f5f09498646a.png">

To turn auto play on/off or change transition duration etc. use these variables in about.html files
<img width="830" alt="Screen Shot 2020-08-17 at 6 19 06 PM" src="https://user-images.githubusercontent.com/61198087/90449796-29500080-e0b6-11ea-8f7b-cd5f6b530787.png">
