### ISSUE TITLE
hero: reduce amount of white space above and below hero section

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#60]
![image](https://user-images.githubusercontent.com/219043/89907261-7154bc00-dbba-11ea-8e86-fb8d1de7c717.png)

**Comment by faiza-a** [comment]
hero spacing can be changed easily using this variable in variables.sass file

<img width="654" alt="Screen Shot 2020-08-17 at 4 22 11 PM" src="https://user-images.githubusercontent.com/61198087/90441012-38c74d80-e0a6-11ea-8f2d-bd9abee6506d.png">

Here is the screenshot showing 10rem instead of 13rem . but don't like it a lot, i think hero should have some spacing. 

<img width="1789" alt="Screen Shot 2020-08-17 at 4 20 35 PM" src="https://user-images.githubusercontent.com/61198087/90440942-12091700-e0a6-11ea-8621-121c37d436fb.png">

We can also make a full width hero by changing 'is-medium' to 'is-fullheight' in hero-main.html

<img width="565" alt="Screen Shot 2020-08-17 at 4 29 05 PM" src="https://user-images.githubusercontent.com/61198087/90441354-cdca4680-e0a6-11ea-921e-1c0248db6582.png">

it will look like this:

<img width="1792" alt="Screen Shot 2020-08-17 at 4 20 59 PM" src="https://user-images.githubusercontent.com/61198087/90441266-aa070080-e0a6-11ea-8d06-db433d9d1ac5.png">

**Comment by jcfr** [comment]
@lassoan @pieper  Any preferences?

**Comment by pieper** [comment]
Personally, I like the 10rem version, but maybe it's too tight so bigger is okay.

i don't like the idea of the full height since that would look weird in a tall window I think, and wouldn't give visitors the idea that there's more content below.  To me it's nice if people see the carousel and maybe get interested to scroll down.

**Comment by lassoan** [comment]
Fully agree with @pieper

**Comment by jcfr** [comment]
Thanks for the feedback. Closing, height set to `10rem`
