### ISSUE TITLE
Make slicer-org the default (and only) branch?

### ISSUE THREAD

**Issue by ihnorton** [Slicer/slicer.org#8]
Requires admin privileges to change, see below:

https://help.github.com/articles/setting-the-default-branch/

**Comment by pieper** [comment]
Makes sense to me.  I found the current layout confusing at first.

I guess move the README and license material from master to the branch too.

**Comment by ihnorton** [comment]
Ok, content merged [here](https://github.com/Slicer/slicer.org/commit/d808e9fff1277af1e6233ab4a1f1416b6ceeec13). Just need to change the default.

**Comment by jcfr** [comment]
Moving forward, I anticipate to have some maintenance scripts, or a deployment steps, or a "build" step checking for html conformance ... that is why I like the idea of decoupling both.

I also think such scripts and README files would not belong to the content that is being served.

In the mean time,  here are possible suggestions:

1) move content of `slicer-org` branch based to `master` branch under a subdirectory named "site"  and ask Greg to update the deployement script so that the static content is serve content of that folder.

or

2) add checkout instruction to the README: See #9

I would prefer (2)

**Comment by jcfr** [comment]
Sounds good. It will be easy enough to re-asses if needs to be.

**Comment by jcfr** [comment]
I updated the default branch and removed the master branch.

**Comment by ihnorton** [comment]
Great, thanks. This is simpler, and avoids the constant prompts to make a PR from updated `slicer-org` against `master`.

(Any scripts probably could just live in a `scripts/` directory and be excluded from deployment?)
